# Generated by Django 3.1.5 on 2021-01-10 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'verbose_name': 'Категория Приложении',
                'verbose_name_plural': 'Категор_прил',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Apps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('language', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('size', models.FloatField(blank=True)),
                ('award', models.CharField(blank=True, max_length=100)),
                ('place', models.IntegerField(blank=True)),
                ('age', models.IntegerField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apps_list',
                                               to='main.app_category')),
            ],
            options={
                'verbose_name': 'Приложения',
                'verbose_name_plural': 'Приложения',
                'ordering': ['created'],
            },
        ),
    ]
