# Generated by Django 3.1.5 on 2021-02-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_appavatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='download_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
