# Generated by Django 3.1.5 on 2021-01-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='chart',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='apps',
            name='compatibility',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='apps',
            name='developer',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='apps',
            name='language_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apps',
            name='version',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
