# Generated by Django 3.1.5 on 2021-01-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='', max_length=300)),
                ('mini_title', models.CharField(blank=True, max_length=300, null=True)),
                ('body', models.TextField(blank=True, max_length=10000, null=True)),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'post',
                'ordering': ['created'],
            },
        ),
    ]
